name: azurite-stack

services:
  azurite:
    container_name: azurite
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - "10000:10000" # Blob
      - "10001:10001" # Queue
      - "10002:10002" # Table
    networks:
      - azurite-network
    restart: unless-stopped

  wiremock:
    image: sheyenrath/wiremock.net:latest
    container_name: wiremock-net
    ports:
      - "9091:80"
    command: --ReadStaticMappings true
    volumes:
      - ./wiremock/mappings:/app/__admin/mappings
    networks:
      - azurite-network
    restart: unless-stopped
      
networks:
  azurite-network:
    name: azurite-network