name: azurite-stack

services:
  azurite:
    container_name: azurite
    image: mcr.microsoft.com/azure-storage/azurite:3.9.0-table-alpha.1
    ports:
      - 10000 # Blob
      - 10001 # Queue
      - 10002 # Table
    command: >
      azurite
      --blobHost 0.0.0.0
      --queueHost 0.0.0.0
      --tableHost 0.0.0.0
      --location /data
      --loose
      --skipApiVersionCheck
    volumes:
      - azurite-data:/data
    networks:
      - azurite-network
    restart: unless-stopped

volumes:
  azurite-data:
networks:
  azurite-network:
    name: azurite-network