name: azurite-stack

services:
  azurite:
    container_name: azurite
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    networks:
      - azurite-network
    restart: unless-stopped
      
networks:
  azurite-network:
    name: azurite-network