name: azurite-stack

services:
  azurite:
    container_name: azurite
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - "10000:10000" # Blob
      - "10001:10001" # Queue
      - "10002:10002" # Table
    networks:
      - azurite-network
    restart: unless-stopped

  mockserver:
    image: mockserver/mockserver:latest
    container_name: appinsights-mockserver
    ports:
      - "1080:1080" # HTTP
      - "1443:1443" # HTTPS
    environment:
      MOCKSERVER_SERVER_PORT: 1080
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/appinsights-expectations.json
      MOCKSERVER_MAX_LOG_ENTRIES: 1000
      MOCKSERVER_ENABLE_CORS_FOR_API: "true"
      MOCKSERVER_CORS_ALLOW_HEADERS: "Content-Type, x-ms-client-request-id, x-ms-session-id"
    volumes:
      - ./mockserver/config:/config:ro
    networks:
      - azurite-network
    restart: unless-stopped
      
networks:
  azurite-network:
    name: azurite-network